services:
  wildfly:
    #Wildfly server instance for the Jtest Coverage agent
    image: quay.io/wildfly/wildfly:latest
    hostname: chatserver
    container_name: chatserver
    ports:
      - 8080:8080
    command:
      - /bin/bash
      - -lc
      - /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -Djboss.tx.node.id="$$JBOSS_TX_NODE_ID"
    volumes:
      # Shared volume that contains Jtest Coverage Agent jars and properties file.
      - type: volume
        source: shared_volume
        target: /opt/jboss/wildfly/shared
      # Have a copy of the standalone.conf on the host machine before using the below.
      - ./conf/standalone.conf:/opt/jboss/wildfly/bin/standalone.conf:ro
      - ./conf/standalone.xml:/opt/jboss/wildfly/standalone/configuration/standalone.xml:ro
      - ../sim-app/target/chat-server.war:/opt/jboss/wildfly/standalone/deployments/chat-server.war:ro
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: chat
      DB_USER: postgres
      DB_PASSWORD: root
      JBOSS_TX_NODE_ID: chatserver-01
      SIM_TRANSLATE_URL: http://libretranslate:5000/translate
      # Generic Key, made by randomkeygen.com
      CONFIG_ENCRYPTION_KEY: 3SKEIyxGENnTp5VAqOEN9BElhaRrVI9SihXD6P5rMeY=
      SIM_EMAIL_CRYPTO_KEY: 3SKEIyxGENnTp5VAqOEN9BElhaRrVI9SihXD6P5rMeY=
      TZ: America/Los_Angeles
    networks:
      - sim-net
  chatDB:
    image: postgres:latest
    hostname: postgres
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: postgres-volume
        target: /var/lib/postgresql
    networks:
      - sim-net
    environment:
      #Configure root password for Database
      #Default root username for Postgres Database is 'postgres'
      - POSTGRES_PASSWORD=root
  libreTranslate:
    image: libretranslate/libretranslate:latest
    hostname: libretranslate
    container_name: libretranslate
    stdin_open: true
    tty: true
    environment:
      TZ: America/Los_Angeles
    networks:
      - sim-net
networks:
  sim-net:
    external: true
    name: sim-net
volumes:
  shared_volume:
    name: shared_volume
    external: true
  postgres-volume:
    name: postgres-volume