package com.sim.chatserver.term;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import com.sim.chatserver.startup.AppDataSourceHolder;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;

@ApplicationScoped
public class TermsStore {
    // parasoft-suppress SECURITY.WSC.DSER "This CDI store is intentionally non-serializable and blocks Java deserialization entry points."
    // parasoft-suppress SECURITY.WSC.SER "This CDI store is intentionally non-serializable and blocks Java serialization entry points."

    private static final Logger log = Logger.getLogger(TermsStore.class.getName());

    private static final String DEFAULT_OTHER = "Other Parasoft Match";

    private AppDataSourceHolder dsHolder;

    public TermsStore() {
        // proxyable no-arg constructor
    }

    @SuppressWarnings("unused")
    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException {
        throw new java.io.NotSerializableException(getClass().getName());
    }

    @SuppressWarnings("unused")
    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
        throw new java.io.NotSerializableException(getClass().getName());
    }

    @Inject
    public void setDataSourceHolder(AppDataSourceHolder dsHolder) {
        this.dsHolder = dsHolder;
    }

    public void ensureTable() throws SQLException {
        try (Connection conn = dsHolder.getDataSource().getConnection()) {
            String product = "";
            try {
                DatabaseMetaData meta = conn.getMetaData();
                if (meta != null && meta.getDatabaseProductName() != null) {
                    product = meta.getDatabaseProductName().toLowerCase();
                }
            } catch (SQLException e) {
                // Defensive fallback to generic SQL when metadata is unavailable.
                log.log(Level.FINE, "Unable to resolve database product metadata", e);
                product = "";
            }

            final boolean isPostgres = product.contains("postgres");
            final boolean isH2 = product.contains("h2");

            final String sql;
            if (isPostgres) {
                sql = "CREATE TABLE IF NOT EXISTS term_definition ("
                        + "id SERIAL PRIMARY KEY, "
                        + "name TEXT UNIQUE NOT NULL, "
                        + "description TEXT NOT NULL, "
                        + "match_pattern TEXT NOT NULL DEFAULT '', "
                        + "match_type TEXT NOT NULL DEFAULT 'WILDCARD', "
                        + "system_flag BOOLEAN NOT NULL DEFAULT FALSE, "
                        + "created_at TIMESTAMPTZ NOT NULL DEFAULT now()"
                        + ')';
            } else if (isH2) {
                sql = "CREATE TABLE IF NOT EXISTS term_definition ("
                        + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                        + "name VARCHAR(1024) UNIQUE NOT NULL, "
                        + "description VARCHAR(4096) NOT NULL, "
                        + "match_pattern VARCHAR(8192) NOT NULL DEFAULT '', "
                        + "match_type VARCHAR(64) NOT NULL DEFAULT 'WILDCARD', "
                        + "system_flag BOOLEAN NOT NULL DEFAULT FALSE, "
                        + "created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP"
                        + ')';
            } else {
                sql = "CREATE TABLE IF NOT EXISTS term_definition ("
                        + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                        + "name TEXT UNIQUE NOT NULL, "
                        + "description TEXT NOT NULL, "
                        + "match_pattern TEXT NOT NULL DEFAULT '', "
                        + "match_type TEXT NOT NULL DEFAULT 'WILDCARD', "
                        + "system_flag BOOLEAN NOT NULL DEFAULT FALSE, "
                        + "created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP"
                        + ')';
            }

            try (PreparedStatement stmt = conn.prepareStatement(sql)) {
                stmt.execute();
            }
        }
        ensureDefaultTerms();
    }

    private void ensureDefaultTerms() throws SQLException {
        upsertSystemTerm(DEFAULT_OTHER,
                "Fallback when no configured term is matched.",
                "", "OTHER");
    }

    private void upsertSystemTerm(String name, String description, String pattern, String type) throws SQLException {
        final String sanitizedName = TextSanitizer.sanitizeForStorage(name);
        final String sanitizedDescription = TextSanitizer.sanitizeForStorage(description);
        final String sanitizedType = normalizeMatchType(type);
        final String sanitizedPattern = TextSanitizer.sanitizePatternForStorage(pattern, sanitizedType);

        try (Connection conn = dsHolder.getDataSource().getConnection(); PreparedStatement ps = conn.prepareStatement(
                "INSERT INTO term_definition (name, description, match_pattern, match_type, system_flag) "
                + "VALUES (?, ?, ?, ?, TRUE) "
                + "ON CONFLICT (name) DO UPDATE SET "
                + "description = EXCLUDED.description, "
                + "match_pattern = EXCLUDED.match_pattern, "
                + "match_type = EXCLUDED.match_type, "
                + "system_flag = TRUE")) {
            ps.setString(1, sanitizedName);
            ps.setString(2, sanitizedDescription);
            ps.setString(3, sanitizedPattern);
            ps.setString(4, sanitizedType);
            ps.executeUpdate();
        } catch (SQLException e) {
            log.log(Level.FINE, "Upsert failed; trying update+insert fallback for term {0}", sanitizedName);
            try (Connection conn = dsHolder.getDataSource().getConnection(); PreparedStatement upd = conn.prepareStatement(
                    "UPDATE term_definition SET description = ?, match_pattern = ?, match_type = ?, system_flag = TRUE WHERE name = ?")) {
                upd.setString(1, sanitizedDescription);
                upd.setString(2, sanitizedPattern);
                upd.setString(3, sanitizedType);
                upd.setString(4, sanitizedName);
                int updated = upd.executeUpdate();
                if (updated > 0) {
                    return;
                }
            }

            try (Connection conn = dsHolder.getDataSource().getConnection(); PreparedStatement ins = conn.prepareStatement(
                    "INSERT INTO term_definition (name, description, match_pattern, match_type, system_flag) VALUES (?, ?, ?, ?, TRUE)")) {
                ins.setString(1, sanitizedName);
                ins.setString(2, sanitizedDescription);
                ins.setString(3, sanitizedPattern);
                ins.setString(4, sanitizedType);
                ins.executeUpdate();
            }
        }
    }

    public List<TermDefinition> listAll() throws SQLException {
        List<TermDefinition> terms = new ArrayList<>();
        try (Connection conn = dsHolder.getDataSource().getConnection(); PreparedStatement ps = conn.prepareStatement(
                "SELECT id, name, description, match_pattern, match_type, system_flag FROM term_definition ORDER BY name ASC"); ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                terms.add(new TermDefinition(
                        readNonNegativeLong(rs, "id"),
                        readSafeDbText(rs, "name", 1024),
                        readSafeDbText(rs, "description", 4096),
                        readSafeDbText(rs, "match_pattern", 8192),
                        readSafeDbText(rs, "match_type", 64),
                        rs.getBoolean("system_flag")
                ));
            }
        }
        return terms;
    }

    public TermDefinition createTerm(String name, String description, String pattern, String type) throws SQLException {
        final String sanitizedName = TextSanitizer.sanitizeForStorage(name);
        final String sanitizedDescription = TextSanitizer.sanitizeForStorage(description);
        final String sanitizedType = normalizeMatchType(type);
        final String sanitizedPattern = TextSanitizer.sanitizePatternForStorage(pattern, sanitizedType);

        try (Connection conn = dsHolder.getDataSource().getConnection(); PreparedStatement ps = conn.prepareStatement(
                "INSERT INTO term_definition (name, description, match_pattern, match_type, system_flag) VALUES (?, ?, ?, ?, FALSE) RETURNING id")) {
            ps.setString(1, sanitizedName);
            ps.setString(2, sanitizedDescription);
            ps.setString(3, sanitizedPattern);
            ps.setString(4, sanitizedType);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    return new TermDefinition(rs.getLong(1), sanitizedName, sanitizedDescription, sanitizedPattern, sanitizedType, false);
                }
            }
        } catch (SQLException e) {
            log.log(Level.FINE, "Create term RETURNING fallback path used for term {0}", sanitizedName);
            try (Connection conn = dsHolder.getDataSource().getConnection(); PreparedStatement ps = conn.prepareStatement(
                    "INSERT INTO term_definition (name, description, match_pattern, match_type, system_flag) VALUES (?, ?, ?, ?, FALSE)")) {
                ps.setString(1, sanitizedName);
                ps.setString(2, sanitizedDescription);
                ps.setString(3, sanitizedPattern);
                ps.setString(4, sanitizedType);
                ps.executeUpdate();
            }
            try (Connection conn = dsHolder.getDataSource().getConnection(); PreparedStatement ps = conn.prepareStatement("SELECT id FROM term_definition WHERE name = ?")) {
                ps.setString(1, sanitizedName);
                try (ResultSet rs = ps.executeQuery()) {
                    if (rs.next()) {
                        return new TermDefinition(rs.getLong(1), sanitizedName, sanitizedDescription, sanitizedPattern, sanitizedType, false);
                    }
                }
            }
        }
        return null;
    }

    public TermDefinition updateTerm(Long id, String name, String description, String pattern, String type) throws SQLException {
        long termId = normalizeTermId(id);
        if (termId <= 0L) {
            return null;
        }

        if (isSystemTerm(termId)) {
            return null;
        }

        final String sanitizedName = TextSanitizer.sanitizeForStorage(name);
        final String sanitizedDescription = TextSanitizer.sanitizeForStorage(description);
        final String sanitizedType = normalizeMatchType(type);
        final String sanitizedPattern = TextSanitizer.sanitizePatternForStorage(pattern, sanitizedType);

        try (Connection conn = dsHolder.getDataSource().getConnection(); PreparedStatement ps = conn.prepareStatement(
                "UPDATE term_definition SET name = ?, description = ?, match_pattern = ?, match_type = ? WHERE id = ? RETURNING system_flag")) {
            ps.setString(1, sanitizedName);
            ps.setString(2, sanitizedDescription);
            ps.setString(3, sanitizedPattern);
            ps.setString(4, sanitizedType);
            ps.setLong(5, termId);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    return new TermDefinition(termId, sanitizedName, sanitizedDescription, sanitizedPattern, sanitizedType, rs.getBoolean("system_flag"));
                }
            }
        } catch (SQLException e) {
            log.log(Level.FINE, "Update term RETURNING fallback path used for id {0}", id);
            try (Connection conn = dsHolder.getDataSource().getConnection(); PreparedStatement ps = conn.prepareStatement(
                    "UPDATE term_definition SET name = ?, description = ?, match_pattern = ?, match_type = ? WHERE id = ?")) {
                ps.setString(1, sanitizedName);
                ps.setString(2, sanitizedDescription);
                ps.setString(3, sanitizedPattern);
                ps.setString(4, sanitizedType);
                ps.setLong(5, termId);
                int updated = ps.executeUpdate();
                if (updated > 0) {
                    try (PreparedStatement ps2 = conn.prepareStatement("SELECT system_flag FROM term_definition WHERE id = ?")) {
                        ps2.setLong(1, termId);
                        try (ResultSet rs = ps2.executeQuery()) {
                            if (rs.next()) {
                                return new TermDefinition(termId, sanitizedName, sanitizedDescription, sanitizedPattern, sanitizedType, rs.getBoolean("system_flag"));
                            }
                        }
                    }
                }
            }
        }
        return null;
    }

    public boolean deleteTerm(Long id) throws SQLException {
        long termId = normalizeTermId(id);
        if (termId <= 0L) {
            return false;
        }

        if (isSystemTerm(termId)) {
            return false;
        }
        try (Connection conn = dsHolder.getDataSource().getConnection(); PreparedStatement ps = conn.prepareStatement("DELETE FROM term_definition WHERE id = ?")) {
            ps.setLong(1, termId);
            return ps.executeUpdate() > 0;
        }
    }

    boolean isSystemTerm(long id) throws SQLException {
        if (id <= 0L) {
            return false;
        }
        try (Connection conn = dsHolder.getDataSource().getConnection(); PreparedStatement ps = conn.prepareStatement("SELECT system_flag FROM term_definition WHERE id = ?")) {
            ps.setLong(1, id);
            try (ResultSet rs = ps.executeQuery()) {
                if (!rs.next()) {
                    return false;
                }
                return rs.getBoolean("system_flag");
            }
        }
    }

    public TermDefinition findFirstMatchingTermForPrompt(String prompt) throws SQLException {
        if (prompt == null || prompt.isEmpty()) {
            return null;
        }
        final String sanitized = TextSanitizer.sanitizeForMatching(prompt);
        if (sanitized.isEmpty()) {
            return null;
        }

        return findFirstMatchingTermForPromptFromTerms(sanitized, listAll());
    }

    public TermDefinition findFirstMatchingTermInPrompts(Iterable<String> prompts) throws SQLException {
        if (prompts == null) {
            return null;
        }

        if (prompts instanceof Collection<?> collection && collection.isEmpty()) {
            return null;
        }

        // optimization: one DB read for all prompts
        final List<TermDefinition> terms = listAll();
        if (terms.isEmpty()) {
            return null;
        }

        for (String prompt : prompts) {
            if (prompt == null || prompt.isEmpty()) {
                continue;
            }
            final String sanitized = TextSanitizer.sanitizeForMatching(prompt);
            if (sanitized.isEmpty()) {
                continue;
            }
            TermDefinition found = findFirstMatchingTermForPromptFromTerms(sanitized, terms);
            if (found != null) {
                return found;
            }
        }
        return null;
    }

    private TermDefinition findFirstMatchingTermForPromptFromTerms(String sanitizedPrompt, List<TermDefinition> terms) {
        TermDefinition bestTerm = null;
        int bestStart = Integer.MAX_VALUE;

        for (TermDefinition td : terms) {
            try {
                Pattern p = TermMatcher.buildStrictPattern(td);
                Matcher m = p.matcher(sanitizedPrompt);
                if (m.find()) {
                    int start = m.start();
                    if (start < bestStart) {
                        bestStart = start;
                        bestTerm = td;
                        if (bestStart == 0) {
                            break;
                        }
                    }
                }
            } catch (IllegalArgumentException e) {
                log.log(Level.FINE, "Failed to test term '" + td.getName() + '\'', e);
            }
        }
        return bestTerm;
    }

    private long readNonNegativeLong(ResultSet rs, String column) throws SQLException {
        long value = rs.getLong(column);
        if (rs.wasNull()) {
            return 0L;
        }
        return Math.max(0L, value);
    }

    private String readSafeDbText(ResultSet rs, String column, int maxChars) throws SQLException {
        String value = rs.getString(column);
        if (value == null) {
            return "";
        }
        String normalized = value.replace('\u0000', ' ').replace("\r", "").replace("\n", " ").trim();
        if (normalized.length() > maxChars) {
            return normalized.substring(0, maxChars);
        }
        return normalized;
    }

    private static String normalizeMatchType(String type) {
        if (type == null || type.trim().isEmpty()) {
            return "WILDCARD";
        }
        return type.trim().toUpperCase();
    }

    private long normalizeTermId(Long id) {
        if (id == null) {
            return -1L;
        }
        return id.longValue();
    }
}
